### ISSUE TITLE
Feat: Register User (Vendors & Buyers)

### ISSUE THREAD

**Issue by faid-terence** [atlp-rwanda/knights-ecomm-fe#15]
To be able to use the application and access authenticated routes, Users should be able to Signup and or Register using Sign up forms on the signup route.
Users cannot access the application without logging in without providing an email and password combination
After a user successfully registers, when they click the verification link in the email it should redirect to the deployed frontend login pageCreate a breakdown of steps as tasks under the task attribute below of PT.
The sign up form should present to the user descriptive validation errors incase of any.
The user should receive verification link on email upon successful registration

**Comment by MC-Knight** [comment]
## Implementation plan
### 1. Deliverables at the start of the project.
Users should be able to create account on  e-commerce website using their first name, last name, phone number, gender,  email and password both buyers and vendors. 


#### Data Flow:
1. Implement the UI design.
2. User enters required data.
3. On form submission, the register action is dispatched.
4. Data are send are sent to the backend API.
6. On success, the user is account created, and success message toasted to screen.
7. On failure, error messages are toasted to screen.

**Tools:**
- Use Typescript.
- Use Tailwind CSS.
- Use React Framework.

### 3. Schedule of implementation of the various parts
- Implement the UI designs and API Integration, expected to be completed by Wednesday 19th/06/2024
- Done Testing by Wednesday 19th/06/2024
- The whole task will be completed by  Wednesday 19th/06/2024

### 4. External services, packages or libraries to be used

- **State Management**: `redux`, `react-redux`.
- **Styling**: `Tailwind CSS`.
- **toasting**:`react-hot-toast`
- **form handling**:`react-hook-form`
- **icons**:`lucide-react`
