### ISSUE TITLE
Users should be able to Login with Email and Password (Include social logins)

### ISSUE THREAD

**Issue by faid-terence** [atlp-rwanda/knights-ecomm-fe#16]
### Description
A user will be able to log in to the website using my email and password, as well as through social media accounts (Google), so that he can access his/her account and other service provided for authenticated users.

### Acceptance Criteria
- Users can enter their email and password to log in.
- Users can log in using their social media (Google) accounts.
- Error messages are displayed for incorrect login details.
- Successful login redirects the user to the home page or the last visited page.
- Users' session is maintained across the website until they log out.
- Should present a link for users to Reset their passwords incase of forgotten credentials 

### Developer Notes
- Use React and Redux for building the login interface, managing the login state and handling user sessions.
- Ensure secure storage of authentication tokens.
- Design a both desktop, tablet and mobile login form.
- Validate input fields for email format and password requirements.

**Comment by aimedivin** [comment]
## Implementation plan
### 1. Deliverables at the end of the project.
Users should be able to log in to the e-commerce website using their email and password, as well as through social media accounts. 

### 2. Data flow / Flowchart / Pseudocode / ERD diagrams

#### Data Flow:
1. Implement the UI design.
2. User enters email and password.
3. On form submission, the login action is dispatched.
4. For social login, the respective OAuth flow is initiated.
5. Login credentials are sent to the backend API.
6. On success, the user is authenticated, and tokens are stored.
7. On failure, error messages are displayed.

**Tools:**
- Use Typescript.
- Use Tailwind CSS.
- Use React Framework.

### 3. Schedule of implementation of the various parts
- Implement the UI designs and API Integration, expected to be completed by Thursday 21st/06/2024
- Start Testing by Friday 21st/06/2024
- The whole task will be completed by Monday 24st/06/2024

### 4. External services or libraries to be used

- **State Management**: `redux`, `react-redux`.
- **Styling**: `Tailwind CSS`.
