### ISSUE TITLE
A buyer should be able to leave feedback/reviews for products

### ISSUE THREAD

**Issue by faid-terence** [atlp-rwanda/knights-ecomm-fe#49]
Description
Why

Buyers should be able to share their thoughts on products they have purchased in order to help future buyers make informed decisions.

Acceptance Criteria:

GIVEN that the buyer has purchased a product

WHEN the buyer visits the product page
THEN they should see an option to leave a review
GIVEN that the buyer is leaving a review

WHEN they submit the review form
THEN the review should be saved and displayed on the product page along with other reviews
Dev Notes:

Only buyers who have purchased the product should be able to leave a review.
The form for leaving a review should include fields for rating, title, and comment.
Review moderation should be implemented to prevent inappropriate content.

**Comment by Ndevu12** [comment]
# Implementation Plan

### Update Product Page Component:

- Add a section to display reviews.
- Add a button for leaving a review, visible only to eligible users.

### Create ReviewForm Component:

- Fields: Rating (stars), title, comment.
- Validation: Required fields, appropriate lengths, etc.
- Submit Button: To send review data to the backend.

### Display Reviews:

- Use a useEffect hook to fetch reviews when the product page loads.
- Map through reviews data and display each review.

### Form Submission Logic:

- Use a state to manage form data.
- On form submission, send data to the backend using an API call.
- Update the reviews list with the new review.

### Eligibility Check:

- Fetch user's purchase history on page load.
- Conditionally render the "Leave a Review" button based on purchase history.

### Testing:

- Write unit tests for the review form component.
- Write integration tests for form submission and reviews display.

**Comment by elijahladdie** [comment]
> Description Why
> 
> Buyers should be able to share their thoughts on products they have purchased in order to help future buyers make informed decisions.
> 
> Acceptance Criteria:
> 
> GIVEN that the buyer has purchased a product
> 
> WHEN the buyer visits the product page THEN they should see an option to leave a review GIVEN that the buyer is leaving a review
> 
> WHEN they submit the review form THEN the review should be saved and displayed on the product page along with other reviews Dev Notes:
> 
> Only buyers who have purchased the product should be able to leave a review. The form for leaving a review should include fields for rating, title, and comment. Review moderation should be implemented to prevent inappropriate content.

@faid-terence we dont track ratings we only track comment as feedback
