### ISSUE TITLE
In-app Notifications

### ISSUE THREAD

**Issue by faid-terence** [atlp-rwanda/knights-ecomm-fe#65]
Description:

The "In-app Notifications" feature aims to provide real-time updates and alerts to users within the application. These notifications will keep users informed about important events, updates, and interactions related to their account, orders, and other activities within the app. Notifications will appear as pop-ups or badges and will be accessible from a dedicated notifications panel.

Objectives:

Real-time Updates: Provide instant notifications for events such as order updates, feedback responses, promotional offers, and more.

User Engagement: Increase user engagement by ensuring they are aware of important activities and updates.
Centralized Notifications Panel: Offer a centralized place for users to view and manage all their notifications.

**Comment by Ndevu12** [comment]
# Implementation Plan:

## Notifications Context:

- Create a React context to manage the state of notifications globally.
- Provide functions to fetch notifications, mark them as read, and delete them.

## WebSocket Integration:

- Set up WebSocket connections to receive real-time notifications.
- Ensure WebSocket messages are properly handled and update the notifications state.

## Notification Components:

### Notification Pop-up:

- Develop a component to display real-time pop-up notifications.
- Ensure it handles different types of notifications (e.g., success, warning, info).
- Implement animations for showing and hiding the pop-up.

### Notifications Panel:

- Develop a component to display a list of notifications.
- Include functionality to mark notifications as read or delete them.
- Provide filtering options (e.g., show only unread notifications).

### Notification Badge:

- Create a badge component to indicate the number of unread notifications.
- Ensure it updates in real-time as notifications are received or read.
